### ISSUE TITLE
How to installl saltstack in Rhel5.4 OS

### ISSUE THREAD

**Issue by malasgowda** [saltstack/salt-winrepo#1325]
Hi,

We are unable to install salt-stack in Rhel5.4 OS. Its telling dependency  error

rpm -ivh salt-minion-2016.11.3-2.el5.noarch.rpm
warning: salt-minion-2016.11.3-2.el5.noarch.rpm: Header V3 RSA/SHA1 signature: NOKEY, key ID 42e589e9
error: Failed dependencies:
        /usr/bin/python2.6 is needed by salt-minion-2016.11.3-2.el5.noarch
        salt = 2016.11.3-2.el5 is needed by salt-minion-2016.11.3-2.el5.noarch

but we have installed  pnyton 2.6.8

[root@VMGems-2 ~]# which python
/usr/bin/python
[root@VMGems-2 ~]# /usr/bin/python -V
Python 2.6.8

So unable to procedd with the instalation in Rhel5.4 .

Please suggest how can we proceed

**Comment by lhost** [comment]
Try to import GnuPG key:

`wget -O /etc/pki/rpm-gpg/SALTSTACK-EL5-GPG-KEY.pub --no-check-certificate   https://repo.saltstack.com/yum/redhat/5Server/x86_64/latest/SALTSTACK-EL5-GPG-KEY.pub
rpm --import /etc/pki/rpm-gpg/SALTSTACK-EL5-GPG-KEY.pub
`

**Comment by dmurphy18** [comment]
@malasgowda SaltStack no longer supports Redhat 5 since it has reached it End-Of-Life.
However you should be able to use archived versions of support for Redhat 5 from when it was supported, check instructions from http://repo.saltstack.com/2016.11.html#rhel

That version was installed and tested by QA, however it would have been against Redhat 5.11 at a minimum.  Redhat 5.4 is quite old, however I would attempt using the install Salt Repo rpm as follows  from he above page:

wget https://repo.saltstack.com/yum/redhat/salt-repo-2016.11-1.el5.noarch.rpm
sudo rpm -ivh salt-repo-2016.11-1.el5.noarch.rpm
rm -f salt-repo-2016.11-1.el5.noarch.rpm

Then yum clean all or yum makecache, followed by:

yum install salt-minion

This should include downloading all dependencies from repo.saltstack.com for salt-minion to be functional.

**Comment by dmurphy18** [comment]
@malasgowda BTW, packaging issues are better dealt with by salt-pack, which is where all packaging builds occur, see https://github.com/saltstack/salt-pack
